apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  # name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    email: ${ISSUER_CONTACT_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod
      # name: letsencrypt-staging
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: contour
