kind: Secret
apiVersion: v1
metadata:
  name: oidc-config
  namespace: contour-auth
type: Opaque
stringData:
  auth-svr-config.yaml: |
    address: ":9443"
    issuerURL: "${AAD_ISSUER_URL}"
    redirectURL: "https://aggregator.${DOMAIN_NAME}"
    redirectPath: "/service"
    clientID: "${AAD_APPLICATION_ID}"
    clientSecret: "${AAD_CLIENT_SECRET}"
