apiVersion: apps/v1
kind: Deployment
metadata:
  name: oidc
spec:
  template:
    spec:
      containers:
      - name: oidc
        resources:
          $patch: delete
      volumes:
      - name: oidc-config
        secret:
          secretName: oidc-config
        configMap:
          $patch: delete