apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-ca
spec:
  isCA: true
  commonName: oidc-ca
  secretName: oidc-root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: oidc-issuer
spec:
  ca:
    secretName: oidc-root-secret