apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: aggregator
  namespace: web
spec:
  virtualhost:
    fqdn: aggregator.${DOMAIN_NAME}
    tls:
      secretName: aggregator
  routes:
    - services:
      - name: aggregator
        port: 8080
        weight: 70
      - name: aggregator-2
        port: 8080
        weight: 30
      conditions:
      - prefix: /backend
      pathRewritePolicy:
        replacePrefix:
        - prefix: /backend
          replacement: /
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: aks-helloworld
  namespace: default
spec:
  virtualhost:
    fqdn: aks-helloworld.${DOMAIN_NAME}
  includes:
  - name: default-web
    namespace: default
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: default-web
  namespace: default
spec:
  routes:
    - services:
      - name: aks-helloworld
        port: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aggregator
  namespace: web
spec:
  commonName: aggregator.${DOMAIN_NAME}
  dnsNames:
  - aggregator.${DOMAIN_NAME}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretName: aggregator